apiVersion: apps/v1
kind: Deployment
metadata:
  name: aerospace-prediction-deployment
  labels:
    app: aerospace-prediction-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aerospace-prediction-api
  template:
    metadata:
      labels:
        app: aerospace-prediction-api
    spec:
      containers:
      - name: prediction-container
        image: bouazalmat/aerospace-prediction-api:v1
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "256m"
---
apiVersion: v1
kind: Service
metadata:
  name: aerospace-prediction-service
spec:
  selector:
    app: aerospace-prediction-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
