version: '3.8'

services:
  api:
    build: "./work/api" 
    container_name: aerospace_inference_api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    restart: always

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.2
    container_name: mlflow_tracking_server
    ports:
      - "5050:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri local --default-artifact-root /mlflow/mlruns 
    restart: always
    environment:
      - GUNICORN_CMD_ARGS=--timeout 180

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_dashboard
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: always

  airflow-init:
    image: apache/airflow:2.8.1-python3.11
    container_name: airflow_init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
    volumes:
      - ./airflow:/opt/airflow
    command: version && airflow db init && airflow users create --username admin --password admin --firstname Airflow --lastname Admin --role Admin --email admin@example.com

  airflow-webserver:
    image: apache/airflow:2.8.1-python3.11
    container_name: airflow_webserver
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
    volumes:
      - ./airflow:/opt/airflow
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: webserver
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.8.1-python3.11
    container_name: airflow_scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
    volumes:
      - ./airflow:/opt/airflow
      - .:/opt/airflow/dags/project_root
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: scheduler
    restart: always